### ISSUE TITLE
Reconciliation should use Artsdata IDs when available

### ISSUE THREAD

**Issue by saumier** [culturecreates/capacoa-artsdata-usermeta#2]
The export of data should include Artsdata IDs when available so the reconciliation of orgs done by the Huginn agents can first try to use an Artsdata ID to link or a Wikidata ID, and only resort to text string matching when no Artsdata or Wikidata ID is available.

**Comment by fjjulien** [comment]
As mentioned in this [other issue](https://github.com/culturecreates/artsdata-shortcode/issues/24#issuecomment-1607932504),  Dessa will be responsible for ensuring data quality prior to the initial extraction. If there exists a Wikidata item and/or an Artsdata resource for the organization, she will find them and populate ID(s) in the CAPACOA database. If there is no Wikidata item, she will manually create it (along with the venue items, if applicable).

@saumier If this modus operandi meets your needs, you may close this issue.

**Comment by dlh28** [comment]
If either of you want to tag me directly on GitHub, here's my username

**Comment by fjjulien** [comment]
@dlh28 I updated our [internal data quality processes](https://docs.google.com/document/d/1n3wD-LZ5bGASSXyGm3SgP-JPEzgsw-CECWPZAmbMX_0/edit#heading=h.z6h07vx4wdoy) to include verification of the Artsdata and Wikidata IDs.
