### ISSUE TITLE
Members not extracted (and not displayed in the directory)

### ISSUE THREAD

**Issue by fjjulien** [culturecreates/capacoa-artsdata-usermeta#8]
The list of presenting organizations in [CAPACOA's directory page](https://capacoa.ca/en/member/directory/) is incomplete. The list is sorted in alphabetical order, but it stops at letter "R" with [Riverfront InterArts](https://capacoa.ca/en/member/directory/profile/?uri=http://kg.artsdata.ca/resource/K14-88) and [monstrARTity](https://capacoa.ca/en/member/directory/profile/?uri=http://kg.artsdata.ca/resource/K14-84) (which is not ordered properly). Any member whose operating name starts with S, T, U, V or Y is not listed in the directory. 

## Excerpt from the CAPACOA member directory (at the end of the presenters list)
![image](https://github.com/culturecreates/capacoa-artsdata-usermeta/assets/78500666/aca41be6-cf5e-498c-a011-913aee7716c3)

I looked a few member records in Artsdata to verify if the issue is at the extraction level, and I'm seeing weird things. 

Some members, such as [Vancouver City Theatres](https://kg.artsdata.ca/entity?uri=K14-69), are loaded to Artsdata and were minted from CAPACOA. Others, such as [The Cultch](https://kg.artsdata.ca/entity?uri=K10-138) were minted from Footlight but are nonetheless in Artsdata. However, neither of these Artsdata records have a sameAs pointing their CAPACOA member record (such as we can find in this [Artsdata record for Riverview Arts Centre](https://kg.artsdata.ca/entity?uri=K14-12)).

I looked at the [Artsdata Data Feeds report for CAPACOA](https://kg.artsdata.ca/en/query/show?title=Organization%20entities%20in%20capacoa-members%20%288258%20triples%29&sparql=list_organizations&graph=http://kg.artsdata.ca/culture-creates/huginn/capacoa-members) to verify if the problem was at the extraction level, and looks like it is. When I order the list in reverse alphabetical order, it stops at the letter "R", just as in the directory. It therefore looks like an extraction problem. 

## [Data Feeds Report](https://kg.artsdata.ca/en/query/show?sparql=feeds_all&title=Data+Feeds)
![image](https://github.com/culturecreates/capacoa-artsdata-usermeta/assets/78500666/90973d54-79b9-4a31-b002-699dfbd0600d)

## [Lists of organizations that are CAPACOA members](https://kg.artsdata.ca/en/query/show?title=Organization%20entities%20in%20capacoa-members%20%288258%20triples%29&sparql=list_organizations&graph=http://kg.artsdata.ca/culture-creates/huginn/capacoa-members)
![image](https://github.com/culturecreates/capacoa-artsdata-usermeta/assets/78500666/45690450-c025-4040-9e0c-5ea2413f2734)

Note: The Data Feed report ends with [Riverview Arts Centre](https://kg.artsdata.ca/entity?uri=K14-12), but this an unusual record. It's an organization, but their membership level with CAPACOA is "Individual" rather than "Presenter". Could this odd record be the culprit that creates an error in the Extract-Transform-Load process? I wouldn't think so: the previous record, Riverfront InterArts is also signed up as an Individual member but they have an organization type and they are listed in the CAPACOA public directory.

@dugost @saumier Any idea what the problem could be? [The Data Feed report](https://kg.artsdata.ca/en/query/show?title=Organization%20entities%20in%20capacoa-members%20%288258%20triples%29&sparql=list_organizations&graph=http://kg.artsdata.ca/culture-creates/huginn/capacoa-members) has exactly 150 organization records. Are we be capped at 150 records?

**Comment by fjjulien** [comment]
I notified Chandel that the ETL stopped with the Riverview Arts Centre and I asked her to clean up their member record. I don't anticipate that this will solve the issue, but it needs cleaning up anyway.

**Comment by fjjulien** [comment]
Chandel fixed the Riverview Arts Centre record, and I refreshed CAPACOA's data in Artsdata. This did not resolve the issue.

**Comment by saumier** [comment]
@fjjulien There was indeed a problem with the extraction. The Huginn agents was calling Wordpress with a cap of 200. I extended this to 400. Now there are 197 organizations and  6 people in the Data feed.

<img width="1692" alt="Screenshot 2024-04-23 at 1 00 16 PM" src="https://github.com/culturecreates/capacoa-artsdata-usermeta/assets/419491/ef6a4ef2-4202-4184-9eb0-cce75abcbae7">

**Comment by fjjulien** [comment]
Thanks. The issue is now resolved!
